pythonindia/inpycon2023

next.config.js
package-lock.json
package.json
pages/index.tsx

Hi Team
Please review this PR for github action "inpycon-ci" build fix
github-pages link: https://tpriyanshukrishnan.github.io/inpycon2023/

Next Js Export Fix

---

components/header.js
pages/pycon-landing.tsx

- on looking via mobile view there is no hamburger icon present, so adding it.
- Correcting some grammatical mistakes

Adding Hamburger Menu Icon and Correcting Grammatical errors

---

components/header.js
pages/pycon-landing.tsx

Issue #48
- Most of the item of navbar are not taking or redirecting to the component attached to.
- I have fixed this issue and added links to the Navbar items whose links/ component are present.

adding links to the components of navbar

---

components/HeroBanner.js
components/button.js
components/registration.js
components/sponsor.js
data/calendar.yml

1. Fixed Issue: #62.
2. Created calendar.yml file to fetch the events in hero banner.
3. Imported and replaced button UI elements with Button component.
4. Disabled Buy Ticket and Download Prospectus buttons.
5. Aligned the visual design of the Download Prospectus button to maintain consistency with other buttons.
6. Fixed Issue: #63
7. Fixed typos in Sponsor section.

Bug fixes, UI enhancements, and typo corrections

---

components/coc.js
components/conventioncenter.js
components/footer.tsx
components/header.js
data/coc.md
package-lock.json
package.json
pages/coc.tsx
pages/pycon-landing.tsx
styles/css/style.css

Add COC page and few other changes

---

components/footer.tsx
components/header.js
components/registration.js
pages/pycon-landing.tsx

**Fixes following issues:**
1. https://github.com/pythonindia/inpycon2023/issues/73
2. There should be space between buttons in Registration section. - Mobile design
3. Blog should open up in a new tab. - https://github.com/pythonindia/inpycon2023/issues/72
4. Dotted background image is not visible in footer. Image - /bg-header-dot.png - (In Local env)
5. Mobile design Hamburger menu doesn’t go away when we click on a section.

Fixes console error issue and some functional issues.

---

components/HeroBanner.js
components/registration.js
styles/css/style.css

- update ticket link in hero banner and attend section
- update button css to look more like CTA.
Fixes #84

Update ticket links, update cta button style in hero banner

---

components/HeroBanner.js
components/registration.js
styles/css/style.css

Removed unnecessary css which is not required for a simple transition effect.
Here's how it looks.

Fix: "Buy Tickets" and "Call For Proposal" buttons unique style.

---

styles/css/style.css

Fixed by adding Max Width CSS Media Query.

Fixed bio section overlapping issue in small screen devices

---

components/keynote.js
styles/css/style.css

1. Commented keynote bio page links.
2. Fixed the height of the section for tab screen and added auto-col property so the speaker card looks consistent.

Commented keynote bio page links and fixed the section for tabs

---

components/HeroBanner.js
components/communityPartners.js
components/header.js
components/paragraph.js
components/pricetable.js
components/registration.js
components/sponsor.js
pages/404.tsx
pages/pycon-landing.tsx
styles/css/style.css

1. https://github.com/pythonindia/inpycon2023/issues/109
2. https://github.com/pythonindia/inpycon2023/issues/16

Tickets and Community Partner Section

---

styles/css/style.css

hey, I think this approach can solve the issue, let me know if it works for you, I modified the width to the body and HTML. I noticed some other issues in the responsiveness,  let me know if you want more help

fix banner overflow on mobile

---

data/coc.md
data/faq.md

**Major changes:**
1. Added dev sprint faq.
2. Removed the **Ticket Booking for PyCon India coming soon! Stay Tuned!** heading as the tickets are available now.
3. Modify faq and coc content heading sizes. h1/ h2->h3 and h3->h4. To improve the readability and visual hierarchy.

Devsprint faq and faq, coc heading size modification

---

components/communityPartners.js
components/pricetable.js
styles/css/style.css

1. Previously the Charminar was not completely visible on mobile screen due to size of the layers present in animation. I have modified the hero banner css properties to fix this issue.
2. Remove smooth scroll to eliminate multi-page scrolling issue.
3. Add tickets link to the checkout page.
4. Fix community partners text alignment.
**Before fix:**
**After fix:**

Improve hero banner visibility issue on mobile view

---

components/header.js
next-seo.config.js
package-lock.json
package.json
pages/_app.tsx
pages/faq.tsx

add seo related changes

---

pages/_app.tsx
utils/google-analytics.js

1. Analytics setup: https://github.com/pythonindia/inpycon2023/issues/134

Google analytics setup

---

components/HeroBanner.js
components/pricetable.js
components/tooltip.js
styles/css/style.css

1. Disable CFP CTA button in Hero Section: Disabled it as the deadline was 12 Aug.
2. A DevSprints CTA button in Hero Section
3. Fix tickets sold out issue: The konfhub API is providing incorrect information for Combo tickets by indicating they were not sold out (sold_out: false). To address this, the solution is to adjust the check from soldOut: ticket.sold_out to soldOut: !(ticket.remaining_count > 0) to accurately determine if tickets are still available.

Disable CFP CTA, add DevSprints CTA, fix tickets sold out issue

---

components/journey.js
data/journey.yml

* Updates `journey.yml` with keynote speaker(s) list.
* Journey Carousel now updates full list of keynote speaker(s) based on conference's year.
Closes: https://github.com/pythonindia/inpycon2023/issues/157

components/journery.js: Update Journey Carousel

---

components/tinkeringSpace.js
components/ylw.js
data/tinkeringSpace.md
data/ylw.md
pages/tinkering-space.tsx
pages/ylw.tsx

Need to update the content for YLW page. Will update and mark the PR ready for review.

YLW, Tinkering Space pages

---

_pages-content/about-us.md
_pages-content/aboutus.md

added content for about us page

---

components/HeroBanner.js
components/journey.js
components/sponsor.js
next.config.js
styles/css/style.css

fix accessibility issues, audited by WAVE tool

---

_pages-content/travel.md

**Major Changes**
1. Add accommodation section in travel page.
2. Adjusted heading sizes to ensure uniformity across the website.

Add accommodation assistance form in travel page

---

_pages-content/jobs-board-rules-guidelines.md
components/button.js
components/footer.tsx
components/header.js
components/icons.js
components/jobsBoard.js
components/sponsor.js
pages/jobs/index.jsx
pages/keynote/[speakerFullName].js
styles/css/style.css
tsconfig.json
utils/googleSheets.js

Major Changes:
1. Add Job Board and Jobs Board - Rules and Guidelines Page.
2. Addition of icon in button component and style modifications.
3. Add icons in Icon component and style modifications.
To Do:

Add Jobs Board

---

components/header.js
components/schedule.js
data/schedule.yml
pages/pycon-landing.tsx
styles/css/style.css

WIP Feature/schedule design

---

components/keynote.js
components/workgroupLeads.js

Improve alignment by centering the last keynote speaker and workgroup leads when there's only one in a row.
1. Keynote Speaker Section.
2. WorkGroup Leads Page.

Improve alignment by centering the last keynote speaker and workgroup leads

---

pages/_app.tsx

remove userway

---

components/header.js
components/localUserGroups.js
components/partners.js
components/pricetable.js

**Major Changes**:
1.  Remove home section extra top margin.
3. Updated ticket sold out condition, added end_timestamp check.
4. Add target attribute in Link component for nested nav items.

Fix: remove home section extra margin, ticket condition, open in new tab condition for nested nav items.

---

pages/pycon-landing.tsx

**Major Changes**
1. Remove schedule section from home page as the buttons are already present in hero banner.
2. Added redirection logic to redirect /#schedule to /schedule for backward compatibility.

Remove schedule section from home page and add redirection to schedule page

---

components/HeroBanner.js

Added Countdown for the event using simply JS date object.

add countdown for event

---

components/speakerDetail.jsx

Fix the Social media icons is not be visible #259

---

_pages-content/code-of-conduct.md

add section for transparency report link
